### ISSUE TITLE
Tạo icon website

### ISSUE THREAD

**Issue by dinhvn** [dinhvn/vio#15]
![image](https://cloud.githubusercontent.com/assets/1032480/20057286/52b14606-a51d-11e6-9b2d-e0d32ee82837.png)
Kích thước: x*x

**Comment by circle16** [comment]
ne
![iconsmall](https://cloud.githubusercontent.com/assets/23307740/20467746/57a9acd6-afc0-11e6-9e4f-e75a68049b66.png)

**Comment by circle16** [comment]
ne
![iconsmall](https://cloud.githubusercontent.com/assets/23307740/20467752/841bfb16-afc0-11e6-803c-7af0f9c29c84.png)

**Comment by dinhvn** [comment]
sao nhìn nó giống cái lá thế
